Traceback (most recent call last):
  File "C:\Users\Barry\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Barry\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Barry\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Barry\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Barry\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Barry\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Barry\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Barry\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
G_patient_gxp_path = 'section2_data/section1_networks/patient_coexpression_network.gml'
G_patient_dnam_path = 'section2_data/section1_networks/patient_meth_network.gml'
G_gxp_path = 'section2_data/section1_networks/gene_coexpression_network.gml' 

# Load the GML graphs
G_gxp = nx.read_gml(G_gxp_path)
G_patient_gxp = nx.read_gml(G_patient_gxp_path)
G_patient_dnam = nx.read_gml(G_patient_dnam_path)

# Get all nodes in the graph
G_gxp_nodes_list = list(G_gxp.nodes())
G_patient_gxp_nodes_list = list(G_patient_gxp.nodes())
G_patient_dnam_nodes_list = list(G_patient_dnam.nodes())

# Load raw TCGA datasets
tcga_dnam_path = 'section2_data/ISMB_TCGA_DNAm.pkl' 

tcga_gxp_path = 'section2_data/ISMB_TCGA_GE.pkl'
tcga_gxp = pd.read_pickle(tcga_gxp_path)

# tcga_gxp_df = tcga_gxp['datExpr']
tcga_gxp_df = pd.read_csv('section2_data/tcga_ge_df_symbols_t.csv') # dataset with gene symbols 
tcga_gxp_df.set_index('GENES', inplace=True)
tcqa_gxp_meta = tcga_gxp['datMeta']


print(len(G_gxp_nodes_list))
print(len(G_patient_gxp_nodes_list))
print(len(G_patient_dnam_nodes_list))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<cell line: 6>[1;34m()[0m
[0;32m      3[0m G_gxp_path [38;5;241m=[39m [38;5;124m'[39m[38;5;124msection2_data/section1_networks/gene_coexpression_network.gml[39m[38;5;124m'[39m 
[0;32m      5[0m [38;5;66;03m# Load the GML graphs[39;00m
[1;32m----> 6[0m G_gxp [38;5;241m=[39m [43mnx[49m[38;5;241;43m.[39;49m[43mread_gml[49m[43m([49m[43mG_gxp_path[49m[43m)[49m
[0;32m      7[0m G_patient_gxp [38;5;241m=[39m nx[38;5;241m.[39mread_gml(G_patient_gxp_path)
[0;32m      8[0m G_patient_dnam [38;5;241m=[39m nx[38;5;241m.[39mread_gml(G_patient_dnam_path)

File [1;32m~\anaconda3\lib\site-packages\networkx\utils\decorators.py:770[0m, in [0;36margmap.__call__.<locals>.func[1;34m(_argmap__wrapper, *args, **kwargs)[0m
[0;32m    769[0m [38;5;28;01mdef[39;00m [38;5;21mfunc[39m([38;5;241m*[39margs, __wrapper[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m--> 770[0m     [38;5;28;01mreturn[39;00m argmap[38;5;241m.[39m_lazy_compile(__wrapper)([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32m<class 'networkx.utils.decorators.argmap'> compilation 5:3[0m, in [0;36margmap_read_gml_1[1;34m(path, label, destringizer, backend, **backend_kwargs)[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mbz2[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mcollections[39;00m
[1;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mgzip[39;00m
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01minspect[39;00m
[0;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mitertools[39;00m

File [1;32m~\anaconda3\lib\site-packages\networkx\utils\decorators.py:193[0m, in [0;36mopen_file.<locals>._open_file[1;34m(path)[0m
[0;32m    189[0m [38;5;28;01melse[39;00m:
[0;32m    190[0m     [38;5;66;03m# could be None, or a file handle, in which case the algorithm will deal with it[39;00m
[0;32m    191[0m     [38;5;28;01mreturn[39;00m path, [38;5;28;01mlambda[39;00m: [38;5;28;01mNone[39;00m
[1;32m--> 193[0m fobj [38;5;241m=[39m [43m_dispatch_dict[49m[43m[[49m[43mext[49m[43m][49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m)[49m
[0;32m    194[0m [38;5;28;01mreturn[39;00m fobj, [38;5;28;01mlambda[39;00m: fobj[38;5;241m.[39mclose()

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'section2_data/section1_networks/gene_coexpression_network.gml'
FileNotFoundError: [Errno 2] No such file or directory: 'section2_data/section1_networks/gene_coexpression_network.gml'

